l_english:

 ### Toggle subject colour stuffs
 vu_toggle_subject_colours_overlord_title:0 "§YToggle Your Subjects colouring in.§!"
 vu_toggle_subject_colours_overlord_desc:0 "This will toggle between your subject being coloured in or not. (also colours in your subject's subjects too)"
 vu_toggle_subject_colours_subject_title:0 "§YToggle Yourself and other subjects colouring in.§!"
 vu_toggle_subject_colours_subject_desc:0 "This will toggle between you and other subjects of your overlord being coloured in or not."
 ## Random Theodoro decision
 vu_FEO_GTFO_title:0 "§b Let's get the fuck away from that. §!"
 vu_FEO_GTFO_desc:0 "§R RUN. §!"
 ### Settings Event Chain
 
 VU_SET_Events.01.t: "Victorum Universalis Settings"
 VU_SET_Events.01.d: "Welcome to Victorum Universalis!\nThis event is here to help you set up the most enjoyable experience for the mod.\n\nThe §G'Recommended Mode'§! is how I personally recommend you play if it's your first time with the mod, so you can fully experience all the new provinces, nations, cultures, religions and content the mod adds.\nBut due to all our extra content, the game might run slowly for some, so you could try §T'Performance Mode'§! and see if it helps.\n\nThere is also an event chain where you can manually select each of the options to create the experience you would enjoy!\nEach of the events will also explain how each setting works in case you are interested.\n\nWe hope you enjoy playing this mod as much as we enjoyed making it!\n- The Victorum Universalis Dev Team"
 VU_SET_Events.01.a: "Enable §GRecommended§! Mode" #All the (Recommended) options.
 VU_SET_Events.01.b: "Enable §TPerformance§! Mode" #All the (Performance) options when available, (Recommended) when not.
 VU_SET_Events.01.c: "I wish to pick each option myself"
 
 VU_SET_Events.01.b.tt: "§GThe game may freeze for a minute, but just wait and it will resume.§!"

 VU_SET_Events.02.t: "Specific Settings"
 VU_SET_Events.02.d: "Here you can select from categories, and choose whichever settings suit you.\n\nClosing the settings will apply all selected settings to the game. §RThis is IREVERSIBLE§!"
 VU_SET_Events.02.a: "§TPerformance Settings§!" #Nothing happens
 VU_SET_Events.02.b: "§GGameplay Settings§!" #VU_SET_Events.03 - Gameplay settings
 VU_SET_Events.02.c: "§YClose Settings§!" #Close and Apply settings

 VU_SET_Events.03.t: "Gameplay Settings"
 VU_SET_Events.03.d: "Here you may select what gameplay options you wish to enable/disable."
 VU_SET_Events.03.ay: "§YSubjects colouring in §!§GON§!"
 VU_SET_Events.03.an: "§YSubjects colouring in §!§ROFF§!"
 VU_SET_Events.03.by: "§YHard to Colonise §!§GON§!"
 VU_SET_Events.03.bn: "§YHard to Colonise §!§ROFF§!"
 VU_SET_Events.03.cy: "§YHistorical Colonisation §!§GON§!"
 VU_SET_Events.03.cn: "§YHistorical Colonisation §!§ROFF§!"
 VU_SET_Events.03.q: "Return back"

 VU_SET_Events.04.t: "Performance Settings"
 VU_SET_Events.04.d: "Here you may select what areas you wish to simplify (remove all minor tags that don't affect the gameplay too much)."
 VU_SET_Events.04.ay: "§YExpanded HRE §!§GON§!"
 VU_SET_Events.04.an: "§YExpanded HRE §!§ROFF§!"
 VU_SET_Events.04.by: "§YExpanded Western Europe §!§GON§!"
 VU_SET_Events.04.bn: "§YExpanded Western Europe §!§ROFF§!"
 VU_SET_Events.04.cy: "§YExpanded Italy §!§GON§!"
 VU_SET_Events.04.cn: "§YExpanded Italy §!§ROFF§!"
 VU_SET_Events.04.q: "Return back"

 VU_SET_Events.05.t: "Age Restrictions for Colonization"
 VU_SET_Events.05.d: "Age Restrictions prevents all nations (player and AI) from colonizing specific colonial nations before a certain age is reached (ex. Colonial Louisiana is 'unlocked' in the Age of Absolutism and can't be colonized before that).\n\nRecommended if you'd like to have a more historically accurate game, but can get a bit chaotic when 'Historical Colonisation' is disabled."
 VU_SET_Events.05.a: "Enabled §G(Recommended)§!" #Nothing happens
 VU_SET_Events.05.b: "Disabled" #Disables Age Restrictions

 VU_SET_Events.06.t: "Hard to Colonise"
 VU_SET_Events.06.d: "Provinces which were not colonised before the 1850s have the province modifier 'Hard to Colonise' and can't be colonised before Diplomatic Technology 35 (~1850s). If taken in a war they will be returned to the previous owner or abandoned it (if there is no previous owner).\nNative american, africans and aboriginals aren't affected by it.\n\nRecommended if you want to prevent europeans from taking large chunks of Africa in the 1500s."
 VU_SET_Events.06.a: "Enabled §G(Recommended)§!" #Nothing happens
 VU_SET_Events.06.b: "Disabled" #'Hard to Colonise' province modifier is removed from all provinces